/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CAN Transmitter example
*              for ModusToolbox. The CAN node 1 transmits the button status
*              periodically over the CAN bus. Successful message transmission is
*              indicated by toggling the USER LED.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2022, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"
#include <stdio.h>

/*****************************************************************************
* Defines
******************************************************************************/
/* Declarations for System timer timing */
#define TICKS_PER_SECOND                    10           /* Ticks per Second */

/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT              (0)

/*******************************************************************************
* Variables
*******************************************************************************/
/* Variable for keeping track of Interrupt */
static volatile bool timer_interrupt_flag = false;

/*******************************************************************************
* Function Name: SysTick_Handler
********************************************************************************
* Summary:
* Function called by system timer every 100 milliseconds. The button state is
* sampled and sent over the CAN bus to the receiver. The User LED is toggled to
* indicate successful transmission.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void SysTick_Handler(void)
{
    /* Update CAN message. Sample and send button state. */
    CAN_NODE_LMO_0.can_data_byte[0] = (uint8_t) XMC_GPIO_GetInput(CYBSP_USER_BTN_PORT, CYBSP_USER_BTN_PIN);

    /* Configure data to be transmitted and data length code */
    XMC_CAN_MO_UpdateData(&CAN_NODE_LMO_0);

    /* Send data in CAN_NODE_LMO_0 */
    XMC_CAN_MO_Transmit(&CAN_NODE_LMO_0);

    /* Toggle USER LED1 to indicate that the message is transmitted */
    XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);

    /* Timer interrupt occurs, set the flag to true  */
    timer_interrupt_flag = true;
}


/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. This function performs
*  - initial setup of device
*  - initialize CAN transmit message object and node
*  - can_message a CAN frame periodically
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    #if ENABLE_XMC_DEBUG_PRINT
    /* Assign false to disable printing of debug messages */
    static volatile bool debug_printf = true;
    #endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize printf retarget */
    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);

    #if ENABLE_XMC_DEBUG_PRINT
    printf("Initialization done\r\n");
    #endif

    /* Enable system timer */
    SysTick_Config(SystemCoreClock / TICKS_PER_SECOND);

    while(1)
    {
        #if ENABLE_XMC_DEBUG_PRINT
        if(timer_interrupt_flag == true && debug_printf == true)
        {
            printf("CAN frame sent\r\n");
            debug_printf = false;
        }
        #endif
    }
}

/* [] END OF FILE */
