/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CAN Transmitter example
*              for ModusToolbox. The CAN node 1 transmits the button status 
*              periodically over the CAN bus. Successful message transmission is 
*              indicated by toggling the USER LED.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_can.h"
#include "xmc_scu.h"
#include <stdio.h>

/*****************************************************************************
* Defines
******************************************************************************/
/* Declarations for System timer timing */
#define TICKS_PER_SECOND      10                        /* Ticks per Second */

#ifdef TARGET_KIT_XMC14_BOOT_001

#define CAN_CLOCK_SOURCE      XMC_CAN_CANCLKSRC_MCLK   /* CAN module clock source  - Peripheral Clock*/
#define CAN_FREQUENCY         48000000                 /* Frequency of the CAN module in Hz */

/* Configure CAN TX GPIO mode */
#define CAN_TX_MODE           XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT9

#endif

#ifdef TARGET_KIT_XMC47_RELAX_V1

#define CAN_CLOCK_SOURCE      XMC_CAN_CANCLKSRC_FPERI  /* CAN module clock source  - Peripheral Clock*/
#define CAN_FREQUENCY         144000000                /* Frequency of the CAN module in Hz */

/* Configure CAN TX GPIO mode */
#define CAN_TX_MODE           XMC_GPIO_MODE_OUTPUT_PUSH_PULL | XMC_GPIO_MODE_OUTPUT_ALT2

#endif

#define BAUD_RATE             500000    /* CAN Node baud rate in bps */
#define SAMPLE_POINT          8000      /* Sample Point. Range = [0, 10000] with respect to [0%, 100%] of the total bit time. */
#define SJW                   1         /* Synchronization Jump Width. Range: 0 - 3 */
#define CAN_IDENTIFIER        0xFF      /* 11 bits/ 29 bits CAN identifier. Sets Arbitration register */
#define CAN_IDENTIFIER_MASK   0xFF      /* CAN identifier Mask. Sets mask bits of Acceptance Mask Register */
#define CAN_IDE_MASK          1         /* Identifier Extension Bit of Message Object. Message object receives frames only with matching IDE bit */
#define DATA_LENGTH_BYTES     1         /* CAN data Length. Range: 0 - 8 */
#define NODE1                 1         /* Node1 */
#define MESSAGE_OBJECT        0         /* Message Object 0 */


/*******************************************************************************
* Variables
*******************************************************************************/

/* CAN Bit time configuration structure */
XMC_CAN_NODE_NOMINAL_BIT_TIME_CONFIG_t baud =
{
  .can_frequency   = CAN_FREQUENCY,    /* Frequency of the CAN module in Hz */
  .baudrate        = BAUD_RATE,        /* Node baud rate in bps */
  .sample_point    = SAMPLE_POINT,     /* Sample Point */
  .sjw             = SJW,              /* Synchronization Jump Width */
};

/* CAN message CAN_MO0 */
XMC_CAN_MO_t can_message =
{
  .can_mo_ptr      = CAN_MO0,                                       /* Pointer to the Message Object CAN register */
  .can_priority    = XMC_CAN_ARBITRATION_MODE_IDE_DIR_BASED_PRIO_2, /* Arbitration Mode/Priority */
  .can_identifier  = CAN_IDENTIFIER,                                /* Standard Identifier */
  .can_id_mask     = CAN_IDENTIFIER_MASK,                           /* CAN Identifier of MO */
  .can_id_mode     = XMC_CAN_FRAME_TYPE_STANDARD_11BITS,            /* Standard identifier */
  .can_ide_mask    = CAN_IDE_MASK,                                  /* Identifier Extension Bit */
  .can_data_length = DATA_LENGTH_BYTES,                             /* Message data length */
  .can_mo_type     = XMC_CAN_MO_TYPE_TRANSMSGOBJ                    /* Transmit Message Object */
};


/*******************************************************************************
* Function Name: SysTick_Handler
********************************************************************************
* Summary:
* Function called by system timer every 100 milliseconds. The button state is 
* sampled and sent over the CAN bus to the receiver. The User LED is toggled to 
* indicate successful transmission.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void SysTick_Handler(void)
{
    /* Update CAN message. Sample and send button state. */
    can_message.can_data_byte[0] = (uint8_t) XMC_GPIO_GetInput(CYBSP_USER_BTN_PORT, CYBSP_USER_BTN_PIN);

    /* Configure data to be transmitted and data length code */
    XMC_CAN_MO_UpdateData(&can_message);

    /* Send data in can_message_0 */
    XMC_CAN_MO_Transmit(&can_message);

    /* Toggle USER LED1 to indicate that the message is transmitted */
    XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
}


/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. This function performs
*  - initial setup of device
*  - initialize CAN transmit message object and node
*  - can_message a CAN frame periodically
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Configure the CAN module timer's clock rate */
    XMC_CAN_InitEx(CAN, CAN_CLOCK_SOURCE, CAN_FREQUENCY);

    /* Configure CAN Node baud rate */
    XMC_CAN_NODE_NominalBitTimeConfigureEx(CAN_NODE1, &baud);

    /* NODE 1 initialization */
    /* Allow to change the configuration of the CAN node 1 */
    XMC_CAN_NODE_EnableConfigurationChange(CAN_NODE1);

    /* Disable CAN node participation in CAN traffic */
    XMC_CAN_NODE_SetInitBit(CAN_NODE1);

    /* Set CAN input receive pin */
    XMC_CAN_NODE_SetReceiveInput(CAN_NODE1, XMC_CAN_NODE_RECEIVE_INPUT_RXDCC);

    /* Connect CAN TX pin to the CAN Node 1 */
    XMC_GPIO_SetMode(CYBSP_CAN_TX_PORT, CYBSP_CAN_TX_PIN, CAN_TX_MODE);

    /* Initializes CAN Message Object */
    XMC_CAN_MO_Config(&can_message);

    /* Allocate Message object to Node 1 */
    XMC_CAN_AllocateMOtoNodeList(CAN, NODE1, MESSAGE_OBJECT);

    /* Lock the configuration of CAN node 1 */
    XMC_CAN_NODE_DisableConfigurationChange(CAN_NODE1);

    /* Enable CAN node 1 participation in CAN traffic */
    XMC_CAN_NODE_ResetInitBit(CAN_NODE1);

    /* Enable system timer */
    SysTick_Config(SystemCoreClock / TICKS_PER_SECOND);

    while(1);
}

/* [] END OF FILE */
